// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATbq7M565EvYC7e3U1yexq5t93A5lI_1s',
    appId: '1:997595468011:web:73aa6beb5dd71ada1caeae',
    messagingSenderId: '997595468011',
    projectId: 'circlesonlinemuslim',
    authDomain: 'circlesonlinemuslim.firebaseapp.com',
    storageBucket: 'circlesonlinemuslim.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqKaFkHeAEBjXOIuuS2Bcg8yiZiReMQiM',
    appId: '1:997595468011:android:a887a4ef9e9f50181caeae',
    messagingSenderId: '997595468011',
    projectId: 'circlesonlinemuslim',
    storageBucket: 'circlesonlinemuslim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8qZosRQq-KcDwSNUm4GIlA_ej3j_NNk',
    appId: '1:997595468011:ios:7eb1b84d9fc015c51caeae',
    messagingSenderId: '997595468011',
    projectId: 'circlesonlinemuslim',
    storageBucket: 'circlesonlinemuslim.appspot.com',
    androidClientId: '997595468011-2vvjqu1ps3krngjl6tlbc6mofvrppc2j.apps.googleusercontent.com',
    iosClientId: '997595468011-54t6o667boo1s6hiilt7q9gtpic7fm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlesOnlineMuslimCommunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8qZosRQq-KcDwSNUm4GIlA_ej3j_NNk',
    appId: '1:997595468011:ios:7eb1b84d9fc015c51caeae',
    messagingSenderId: '997595468011',
    projectId: 'circlesonlinemuslim',
    storageBucket: 'circlesonlinemuslim.appspot.com',
    androidClientId: '997595468011-2vvjqu1ps3krngjl6tlbc6mofvrppc2j.apps.googleusercontent.com',
    iosClientId: '997595468011-54t6o667boo1s6hiilt7q9gtpic7fm8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.circlesOnlineMuslimCommunity',
  );
}
